import { network } from "hardhat";
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "fs";
import { resolve } from "path";

const MANAGED_ENV_KEYS = new Set([
    "NEXT_PUBLIC_REGISTRY_ADDRESS",
    "NEXT_PUBLIC_VERIFIER_ADDRESS",
    "NEXT_PUBLIC_NETWORK_NAME",
]);

function updateAppEnvFile(envPath: string, networkName: string, registryAddr: string, verifierAddr: string) {
    const existingEnv = existsSync(envPath)
        ? readFileSync(envPath, "utf8")
        : "";

    const preservedLines = existingEnv
        .split(/\r?\n/)
        .filter((line) => {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith("#")) return false;
            const key = trimmed.split("=", 1)[0];
            return !MANAGED_ENV_KEYS.has(key);
        });

    const envContent = `# Auto-generated by deploy script on ${new Date().toISOString()}\nNEXT_PUBLIC_REGISTRY_ADDRESS=${registryAddr}\nNEXT_PUBLIC_VERIFIER_ADDRESS=${verifierAddr}\nNEXT_PUBLIC_NETWORK_NAME=${networkName}\n${preservedLines.length ? `\n${preservedLines.join("\n")}\n` : ""}`;

    mkdirSync(resolve(envPath, ".."), { recursive: true });
    writeFileSync(envPath, envContent);
}

async function main() {
    const { ethers } = (await network.connect()) as any;

    const verifier = await ethers.deployContract("Groth16Verifier");
    const verifierAddr = await verifier.getAddress();
    console.log("Groth16Verifier:", verifierAddr);

    const registry = await ethers.deployContract("WhistleblowerRegistry", [verifierAddr]);
    const registryAddr = await registry.getAddress();
    console.log("WhistleblowerRegistry:", registryAddr);

    // Save addresses for both app env files in the monorepo.
    const chain = await ethers.provider.getNetwork();
    const chainId = Number(chain.chainId);
    const networkName =
        chainId === 11155111
            ? "sepolia"
            : chainId === 31337
              ? "localhost"
              : process.env.HARDHAT_NETWORK ?? (network as { name?: string }).name ?? String(chainId);
    const adminEnvPath = resolve(import.meta.dirname, "../apps/admin/.env.local");
    const reporterEnvPath = resolve(import.meta.dirname, "../apps/reporter/.env.local");

    updateAppEnvFile(adminEnvPath, networkName, registryAddr, verifierAddr);
    updateAppEnvFile(reporterEnvPath, networkName, registryAddr, verifierAddr);

    console.log(`\n✓ Addresses saved to:`);
    console.log(`  - apps/admin/.env.local`);
    console.log(`  - apps/reporter/.env.local`);
    console.log(`\nFor local development, apps should auto-detect localhost.`);
    console.log(`For testnet (${networkName}), update app env values manually if needed.`);
}

main().catch(console.error);
